export const initialState = {
  token: null,
  isLoggedIn: false,
  profile: {
  },
  errors: [],
  registrationSuccess: false,
  registrationDoctorSuccess: false,
  registrationDoctorError: false,
  loading: false,
  profileUpdateSuccess: false,
  adminRegisteredUserTokens: '',
  cardiologist: [],
  dentist: [],
  dermatologist: [],
  generalSurgeon: [],
  neurologist: [],
  oncologist: [],
  ophthalmologist: [],
  pediatrician: [],
  primaryCarePhysician: [],
  radiologist: [],
  allDoctors: [],
  doctorApptProfile: {
  },
  paymentSuccess: false,
  emailSuccess: false,
  uniqueApptArr: [],
  userDelete: false,
  noUserExist: false,
  adminViewData: {},
  commentSuccess: false
};